function words(s) {
  return new Set(s.trim().split(/\s+/).filter(Boolean));
}

const VOCAB = Object.freeze({
  kinds: {
    ACTION: "action",
    DIRECTIVE: "directive",
    ENTITY: "entity",
    METRIC: "metric",
    ATTRIBUTE: "attribute",
    QUALIFIER: "qualifier",
    QUANTITY: "quantity",
    TIME: "time",
    MONEY: "money",
    COMPARATOR: "comparator",
    PRONOUN: "pronoun",
    DETERMINER: "determiner",
    PREPOSITION: "preposition",
    CONJUNCTION: "conjunction",
    AUXILIARY: "auxiliary",
    MODAL: "modal",
    NEGATION: "negation",
    CONDITION: "condition",
    CADENCE: "cadence",
    STRUCTURAL: "structural",
    UNKNOWN: "unknown",
  },

  concepts: {
    REQUEST: "Request",
    INTENT: "Intent",
    PLAN: "Plan",
    STEP: "Step",
    SUBJECT: "Subject",
    OBJECT: "Object",
    SOURCE: "Source",
    TARGET: "Target",
    OUTPUT: "Output",
    VALUE: "Value",
    ACTION: "Action",
    DIRECTIVE: "Directive",
    CONSTRAINT: "Constraint",
    CONDITION: "Condition",
    THRESHOLD: "Threshold",
    CADENCE: "Cadence",
    TOOL: "Tool",
    POLICY: "Policy",
    AMBIGUITY: "Ambiguity",
  },

  relations: {
    HAS_INTENT: "has_intent",
    HAS_PLAN: "has_plan",
    HAS_STEP: "has_step",
    HAS_ACTION: "has_action",
    HAS_DIRECTIVE: "has_directive",
    HAS_OBJECT: "has_object",
    HAS_SUBJECT: "has_subject",
    HAS_SOURCE: "has_source",
    HAS_TARGET: "has_target",
    HAS_OUTPUT: "has_output",
    HAS_VALUE: "has_value",
    HAS_CONSTRAINT: "has_constraint",
    HAS_CONDITION: "has_condition",
    HAS_THRESHOLD: "has_threshold",
    HAS_CADENCE: "has_cadence",
    QUALIFIES: "qualifies",
    REFERS_TO: "refers_to",
    DEPENDS_ON: "depends_on",
    REQUIRES: "requires",
    PRODUCES: "produces",
    COMPILES_TO: "compiles_to",
    BLOCKED_BY: "blocked_by",
  },

  intents: {
    CREATE_REMINDER: "CreateReminder",
    COMPARE: "Compare",
    MONITOR: "Monitor",
    SUMMARIZE: "Summarize",
    EXTRACT: "Extract",
    BUILD: "Build",
    CREATE: "Create",
    SEARCH: "Search",
    ANALYZE: "Analyze",
    UPDATE: "Update",
    DELETE: "Delete",
    SEND: "Send",
    READ: "Read",
    STASH: "Stash",
    REVERT: "Revert",
    RESET: "Reset",
    MOVE: "Move",
    UNKNOWN: "UnknownIntent",
  },

  directives: {
    NOTIFY: "Notify",
    ALERT: "Alert",
    REMIND: "Remind",
    SCHEDULE: "Schedule",
    WATCH: "Watch",
    EXPLAIN: "Explain",
    COMPRESS: "Compress",
    EXPORT: "Export",
    VALIDATE: "Validate",
  },

  operators: {
    GT: ">",
    GTE: ">=",
    LT: "<",
    LTE: "<=",
    EQ: "=",
    NEQ: "!=",
    APPROX: "~",
  },
});

const CORE = Object.freeze({
  determiners: words("the a an this that these those each every all some any no another other same"),

  pronouns: {
    i: "speaker",
    me: "speaker",
    my: "speaker.possessive",
    mine: "speaker.possessive",
    we: "speaker_group",
    us: "speaker_group",
    our: "speaker_group.possessive",
    you: "addressee",
    your: "addressee.possessive",
    he: "third_person.male",
    him: "third_person.male",
    she: "third_person.female",
    her: "third_person.female",
    it: "anaphora.nearest_nonhuman",
    they: "third_person.plural",
    them: "third_person.plural",
    their: "third_person.plural.possessive",
    who: "interrogative.person",
    what: "interrogative.thing",
    where: "interrogative.place",
    why: "interrogative.reason",
    how: "interrogative.method",
  },

  auxiliaries: words("am is are was were be been being do does did have has had"),
  modals: words("will would shall should can could may might must need needs needed want wants wanted"),
  negations: words("not never none cannot can't won't don't doesn't didn't isn't aren't wasn't weren't no without"),

  conjunctions: {
    and: "AND",
    or: "OR",
    but: "BUT",
    nor: "NOR",
    yet: "YET",
    so: "SO",
    then: "THEN",
    than: "THAN",
    because: "BECAUSE",
    while: "WHILE",
    although: "ALTHOUGH",
  },

  prepositions: {
    of: "OF",
    in: "IN",
    on: "ON",
    at: "AT",
    by: "BY",
    for: "FOR",
    to: "TO",
    from: "FROM",
    with: "WITH",
    without: "WITHOUT",
    into: "INTO",
    onto: "ONTO",
    between: "BETWEEN",
    through: "THROUGH",
    during: "DURING",
    before: "BEFORE",
    after: "AFTER",
    about: "ABOUT",
    around: "AROUND",
    across: "ACROSS",
    against: "AGAINST",
    within: "WITHIN",
  },

  conditionMarkers: {
    if: "If",
    when: "When",
    whenever: "Whenever",
    unless: "Unless",
    until: "Until",
    once: "Once",
  },

  comparatorWords: {
    exceeds: VOCAB.operators.GT,
    exceed: VOCAB.operators.GT,
    above: VOCAB.operators.GT,
    over: VOCAB.operators.GT,
    greater: VOCAB.operators.GT,
    higher: VOCAB.operators.GT,
    more: VOCAB.operators.GT,
    below: VOCAB.operators.LT,
    under: VOCAB.operators.LT,
    less: VOCAB.operators.LT,
    lower: VOCAB.operators.LT,
    fewer: VOCAB.operators.LT,
    equals: VOCAB.operators.EQ,
    equal: VOCAB.operators.EQ,
    differs: VOCAB.operators.NEQ,
    different: VOCAB.operators.NEQ,
    changed: VOCAB.operators.NEQ,
    approximately: VOCAB.operators.APPROX,
    roughly: VOCAB.operators.APPROX,
  },

  time: {
    now: "Instant:now",
    today: "RelativeDate:today",
    tomorrow: "RelativeDate:tomorrow",
    yesterday: "RelativeDate:yesterday",
    tonight: "TimeBucket:night",
    morning: "TimeBucket:morning",
    afternoon: "TimeBucket:afternoon",
    evening: "TimeBucket:evening",
    night: "TimeBucket:night",
    monday: "Weekday:monday",
    tuesday: "Weekday:tuesday",
    wednesday: "Weekday:wednesday",
    thursday: "Weekday:thursday",
    friday: "Weekday:friday",
    saturday: "Weekday:saturday",
    sunday: "Weekday:sunday",
  },

  cadence: {
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    hourly: "Hourly",
    nightly: "Nightly",
    repeatedly: "Repeated",
    recurring: "Repeated",
    always: "Always",
  },

  qualifiers: {
    east: "Region:east",
    west: "Region:west",
    north: "Region:north",
    south: "Region:south",
    left: "Side:left",
    right: "Side:right",
    upper: "Direction:up",
    lower: "Direction:down",
    first: "Ordinal:first",
    second: "Ordinal:second",
    third: "Ordinal:third",
    last: "Ordinal:last",
    next: "Ordinal:next",
    previous: "Ordinal:previous",
    old: "State:old",
    new: "State:new",
    current: "State:current",
    last: "Temporal:last",
    this: "Temporal:this",
    latest: "State:latest",
    local: "Scope:local",
    recursive: "Scope:recursive",
    primary: "Role:primary",
    secondary: "Role:secondary",
    source: "Role:source",
    target: "Role:target",
    fast: "Property:fast",
    slow: "Property:slow",
    high: "Property:high",
    low: "Property:low",
    up: "Direction:up",
    down: "Direction:down",
    black: "Color:black",
    white: "Color:white",
    red: "Color:red",
    crimson: "Color:crimson",
    scarlet: "Color:scarlet",
    blue: "Color:blue",
    navy: "Color:navy",
    cyan: "Color:cyan",
    teal: "Color:teal",
    green: "Color:green",
    lime: "Color:lime",
    emerald: "Color:emerald",
    yellow: "Color:yellow",
    gold: "Color:gold",
    orange: "Color:orange",
    amber: "Color:amber",
    purple: "Color:purple",
    violet: "Color:violet",
    magenta: "Color:magenta",
    pink: "Color:pink",
    brown: "Color:brown",
    gray: "Color:gray",
    grey: "Color:gray",
    silver: "Color:silver",
    pastel: "ColorModifier:pastel",
    vivid: "ColorModifier:vivid",
    neon: "ColorModifier:neon",
    muted: "ColorModifier:muted",
  },

  actions: {
    add: VOCAB.intents.CREATE,
    analyze: VOCAB.intents.ANALYZE,
    build: VOCAB.intents.BUILD,
    check: VOCAB.intents.MONITOR,
    change: VOCAB.intents.UPDATE,
    compare: VOCAB.intents.COMPARE,
    compile: VOCAB.intents.BUILD,
    create: VOCAB.intents.CREATE,
    delete: VOCAB.intents.DELETE,
    erase: VOCAB.intents.DELETE,
    remove: VOCAB.intents.DELETE,
    diff: VOCAB.intents.COMPARE,
    explain: VOCAB.intents.SUMMARIZE,
    export: VOCAB.intents.SEND,
    extract: VOCAB.intents.EXTRACT,
    find: VOCAB.intents.SEARCH,
    generate: VOCAB.intents.BUILD,
    get: VOCAB.intents.READ,
    grow: VOCAB.intents.UPDATE,
    brighten: VOCAB.intents.UPDATE,
    darken: VOCAB.intents.UPDATE,
    lighten: VOCAB.intents.UPDATE,
    saturate: VOCAB.intents.UPDATE,
    desaturate: VOCAB.intents.UPDATE,
    recolor: VOCAB.intents.UPDATE,
    increase: VOCAB.intents.UPDATE,
    decrease: VOCAB.intents.UPDATE,
    raise: VOCAB.intents.UPDATE,
    lower: VOCAB.intents.UPDATE,
    boost: VOCAB.intents.UPDATE,
    enlarge: VOCAB.intents.UPDATE,
    expand: VOCAB.intents.UPDATE,
    inflate: VOCAB.intents.UPDATE,
    list: VOCAB.intents.READ,
    load: VOCAB.intents.READ,
    make: VOCAB.intents.CREATE,
    monitor: VOCAB.intents.MONITOR,
    move: VOCAB.intents.MOVE,
    nudge: VOCAB.intents.MOVE,
    read: VOCAB.intents.READ,
    reconcile: VOCAB.intents.COMPARE,
    revert: VOCAB.intents.REVERT,
    reset: VOCAB.intents.RESET,
    search: VOCAB.intents.SEARCH,
    stash: VOCAB.intents.STASH,
    send: VOCAB.intents.SEND,
    set: VOCAB.intents.UPDATE,
    shift: VOCAB.intents.MOVE,
    shrink: VOCAB.intents.UPDATE,
    reduce: VOCAB.intents.UPDATE,
    contract: VOCAB.intents.UPDATE,
    slide: VOCAB.intents.MOVE,
    push: VOCAB.intents.MOVE,
    pull: VOCAB.intents.MOVE,
    scoot: VOCAB.intents.MOVE,
    rotate: VOCAB.intents.UPDATE,
    spin: VOCAB.intents.UPDATE,
    twist: VOCAB.intents.UPDATE,
    tilt: VOCAB.intents.UPDATE,
    summarize: VOCAB.intents.SUMMARIZE,
    turn: VOCAB.intents.UPDATE,
    update: VOCAB.intents.UPDATE,
    validate: VOCAB.intents.ANALYZE,
    watch: VOCAB.intents.MONITOR,
    write: VOCAB.intents.CREATE,
  },

  directives: {
    alert: VOCAB.directives.ALERT,
    notify: VOCAB.directives.NOTIFY,
    remind: VOCAB.directives.REMIND,
    schedule: VOCAB.directives.SCHEDULE,
    watch: VOCAB.directives.WATCH,
    explain: VOCAB.directives.EXPLAIN,
    compress: VOCAB.directives.COMPRESS,
    export: VOCAB.directives.EXPORT,
    validate: VOCAB.directives.VALIDATE,
  },

  entities: {
    account: "BusinessObject:account",
    accounts: "BusinessObject:account",
    agent: "Actor:agent",
    agents: "Actor:agent",
    api: "System:api",
    app: "Software:app",
    application: "Software:application",
    shape: "UI:shape",
    shapes: "UI:shape",
    ball: "UI:ball",
    balls: "UI:ball",
    orb: "UI:ball",
    sphere: "UI:ball",
    circle: "UI:ball",
    dot: "UI:ball",
    square: "UI:square",
    squares: "UI:square",
    boxy: "UI:square",
    triangle: "UI:triangle",
    triangles: "UI:triangle",
    pyramid: "UI:triangle",
    boiler: "PhysicalSystem:boiler",
    box: "UI:textbox",
    button: "UI:button",
    calendar: "System:calendar",
    call: "Operation:call",
    calls: "Operation:call",
    code: "Document:code",
    database: "DataStore:database",
    data: "Data:data",
    deck: "Document:deck",
    doc: "Document:document",
    document: "Document:document",
    documents: "Document:document",
    email: "Message:email",
    event: "TemporalObject:event",
    file: "Document:file",
    files: "Document:file",
    log: "Document:log",
    logs: "Document:log",
    markdown: "Document:markdown",
    md: "Document:markdown",
    pdf: "Document:pdf",
    pdfs: "Document:pdf",
    commit: "GitObject:commit",
    commits: "GitObject:commit",
    change: "GitObject:change",
    changes: "GitObject:change",
    graph: "Structure:graph",
    image: "Media:image",
    index: "SearchIndex",
    indexes: "SearchIndex",
    indices: "SearchIndex",
    issue: "WorkItem:issue",
    job: "Process:job",
    message: "Message:message",
    plan: "Structure:plan",
    report: "Document:report",
    repo: "Codebase:repository",
    repository: "Codebase:repository",
    request: "Interaction:request",
    result: "Output:result",
    service: "System:service",
    slide: "Document:slide",
    slides: "Document:slide",
    table: "Data:table",
    task: "WorkItem:task",
    text: "Document:text",
    textbox: "UI:textbox",
    tool: "System:tool",
    tools: "System:tool",
    user: "Actor:user",
  },

  metrics: {
    angle: "Metric:rotation",
    color: "Metric:color",
    hue: "Metric:hue",
    saturation: "Metric:saturation",
    lightness: "Metric:lightness",
    brightness: "Metric:lightness",
    size: "Metric:size",
    radius: "Metric:size",
    diameter: "Metric:size",
    width: "Metric:size",
    rotation: "Metric:rotation",
    cost: "Metric:cost",
    count: "Metric:count",
    drift: "Metric:drift",
    error: "Metric:error",
    errors: "Metric:error",
    failure: "Metric:failure",
    failures: "Metric:failure",
    latency: "Metric:latency",
    rate: "Metric:rate",
    score: "Metric:score",
    speed: "Metric:speed",
    time: "Metric:time",
    week: "Metric:time",
    weeks: "Metric:time",
    total: "Metric:total",
    usage: "Metric:usage",
    value: "Metric:value",
    volume: "Metric:volume",
  },

  domainModifiers: {
    search: "DomainModifier:search",
    ai: "DomainModifier:ai",
    agent: "DomainModifier:agent",
    vector: "DomainModifier:vector",
    semantic: "DomainModifier:semantic",
    hybrid: "DomainModifier:hybrid",
  },

  structural: words(`
    again almost also already among amount as ask back bad best better big both bring came come comes
    day days down end enough even ever far few give going good got great help here home just keep kind
    know large let like little long look made many maybe most much near only open own part people place
    put really right said see seem seen small still such take tell thing things think though thought
    three too two up use used using very way well went work world yes
  `),
});

const TOOL_HINTS = Object.freeze({
  [VOCAB.intents.CREATE_REMINDER]: ["calendar.createReminder"],
  [VOCAB.intents.COMPARE]: ["analysis.compare"],
  [VOCAB.intents.MONITOR]: ["scheduler.createWatch"],
  [VOCAB.intents.MOVE]: ["ui.moveBall"],
  [VOCAB.intents.SUMMARIZE]: ["language.summarize"],
  [VOCAB.intents.EXTRACT]: ["language.extract"],
  [VOCAB.intents.BUILD]: ["document.build"],
  [VOCAB.intents.CREATE]: ["object.create"],
  [VOCAB.intents.READ]: ["object.read"],
  [VOCAB.intents.SEARCH]: ["search.query"],
  [VOCAB.intents.SEND]: ["message.send"],
  [VOCAB.intents.UPDATE]: ["ui.setBallColor", "ui.setText"],
  [VOCAB.directives.NOTIFY]: ["notification.send"],
  [VOCAB.directives.ALERT]: ["notification.send"],
});

const TOOL_SPECS = Object.freeze({
  get_weather: {
    type: "function",
    name: "get_weather",
    description: "Get the current weather and near-term forecast for a city.",
    parameters: {
      type: "object",
      properties: {
        city: {
          type: "string",
          description: "City name, e.g. Boston",
        },
        state: {
          type: "string",
          description: "Optional US state abbreviation, e.g. MA",
        },
        units: {
          type: "string",
          enum: ["fahrenheit", "celsius"],
          default: "fahrenheit",
        },
      },
      required: ["city"],
    },
  },

  data_fetch: {
    type: "function",
    name: "data_fetch",
    description: "Fetch data for a named subject or qualified subject.",
    parameters: {
      type: "object",
      properties: {
        subject: { type: "string" },
        qualifier: { type: "string" },
        source: { type: "string" },
      },
      required: ["subject"],
    },
  },

  analysis_compare: {
    type: "function",
    name: "analysis_compare",
    description: "Compare two fetched values, records, datasets, or subjects.",
    parameters: {
      type: "object",
      properties: {
        left: { type: "string" },
        right: { type: "string" },
        metric: { type: "string" },
      },
      required: ["left", "right"],
    },
  },

  condition_evaluate: {
    type: "function",
    name: "condition_evaluate",
    description: "Evaluate one or more symbolic threshold conditions against observed data.",
    parameters: {
      type: "object",
      properties: {
        input: { type: "string" },
        thresholds: {
          type: "array",
          items: {
            type: "object",
            properties: {
              metric: { type: "string" },
              operator: { type: "string", enum: [">", ">=", "<", "<=", "=", "!=", "~"] },
              value: { type: "number" },
              unit: { type: "string" },
            },
            required: ["operator", "value"],
          },
        },
      },
      required: ["thresholds"],
    },
  },

  notification_send: {
    type: "function",
    name: "notification_send",
    description: "Send a notification after a condition or gate passes.",
    parameters: {
      type: "object",
      properties: {
        message: { type: "string" },
        when: { type: "string" },
      },
      required: ["message"],
    },
  },

  scheduler_create_watch: {
    type: "function",
    name: "scheduler_create_watch",
    description: "Create a recurring or repeated watch over a target.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "array", items: { type: "string" } },
        cadence: { type: "array", items: { type: "string" } },
      },
      required: ["target"],
    },
  },

  object_read: {
    type: "function",
    name: "object_read",
    description: "Read one or more source objects or documents.",
    parameters: {
      type: "object",
      properties: {
        sources: { type: "array", items: { type: "string" } },
      },
      required: ["sources"],
    },
  },

  language_extract: {
    type: "function",
    name: "language_extract",
    description: "Extract named values or evidence from prior input.",
    parameters: {
      type: "object",
      properties: {
        from: { type: "string" },
        values: { type: "array", items: { type: "string" } },
      },
      required: ["from", "values"],
    },
  },

  language_summarize: {
    type: "function",
    name: "language_summarize",
    description: "Summarize prior input into concise text.",
    parameters: {
      type: "object",
      properties: {
        input: { type: "string" },
        values: { type: "array", items: { type: "string" } },
      },
      required: ["input"],
    },
  },

  document_build: {
    type: "function",
    name: "document_build",
    description: "Build a document from prior extracted or summarized data.",
    parameters: {
      type: "object",
      properties: {
        outputs: { type: "array", items: { type: "string" } },
        input: { type: "string" },
      },
      required: ["outputs"],
    },
  },

  time_normalize: {
    type: "function",
    name: "time_normalize",
    description: "Normalize symbolic temporal constraints into concrete scheduling values.",
    parameters: {
      type: "object",
      properties: {
        temporal: { type: "array", items: { type: "string" } },
        cadence: { type: "array", items: { type: "string" } },
      },
      required: [],
    },
  },

  calendar_create_reminder: {
    type: "function",
    name: "calendar_create_reminder",
    description: "Create a calendar reminder.",
    parameters: {
      type: "object",
      properties: {
        text: { type: "string" },
        temporal: { type: "string" },
      },
      required: ["text"],
    },
  },

  ui_move_ball: {
    type: "function",
    name: "ui_move_ball",
    description: "Move a persistent demo entity in a named direction by a pixel or percent distance.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string", enum: ["circle", "square", "triangle"] },
        direction: { type: "string", enum: ["left", "right", "up", "down"] },
        distance: { type: "number" },
        unit: { type: "string", enum: ["px", "percent"] },
      },
      required: ["target", "direction", "distance", "unit"],
    },
  },

  ui_set_ball_color: {
    type: "function",
    name: "ui_set_ball_color",
    description: "Set a persistent demo entity to a named color.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string", enum: ["circle", "square", "triangle"] },
        color: { type: "string" },
      },
      required: ["target", "color"],
    },
  },

  ui_adjust_shape_color: {
    type: "function",
    name: "ui_adjust_shape_color",
    description: "Adjust hue, saturation, or lightness on a persistent demo entity.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string", enum: ["circle", "square", "triangle"] },
        operation: {
          type: "string",
          enum: [
            "set_hue",
            "rotate_hue",
            "set_saturation",
            "adjust_saturation",
            "set_lightness",
            "adjust_lightness"
          ],
        },
        value: { type: "number" },
      },
      required: ["target", "operation", "value"],
    },
  },

  ui_resize_ball: {
    type: "function",
    name: "ui_resize_ball",
    description: "Grow or shrink a persistent demo entity by a scale factor.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string", enum: ["circle", "square", "triangle"] },
        operation: { type: "string", enum: ["grow", "shrink"] },
        factor: { type: "number" },
      },
      required: ["target", "operation", "factor"],
    },
  },

  ui_set_shape: {
    type: "function",
    name: "ui_set_shape",
    description: "Morph a tracked demo entity into another shape. Reserved for future identity-aware use.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string", enum: ["circle", "square", "triangle"] },
        shape: { type: "string", enum: ["circle", "square", "triangle"] },
      },
      required: ["target", "shape"],
    },
  },

  ui_rotate_shape: {
    type: "function",
    name: "ui_rotate_shape",
    description: "Rotate a persistent demo entity by a number of degrees.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string", enum: ["circle", "square", "triangle"] },
        degrees: { type: "number" },
      },
      required: ["target", "degrees"],
    },
  },

  ui_set_text: {
    type: "function",
    name: "ui_set_text",
    description: "Set visible text content for a named demo element.",
    parameters: {
      type: "object",
      properties: {
        target: { type: "string" },
        text: { type: "string" },
      },
      required: ["target", "text"],
    },
  },
});

export {
  CORE,
  TOOL_HINTS,
  TOOL_SPECS,
  VOCAB,
};